# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('clinic', models.CharField(max_length=50)),
                ('aging_batch', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('insurance', models.CharField(max_length=100)),
                ('cpt_codes', models.CharField(max_length=100)),
                ('billed_amount', models.IntegerField(default=0)),
                ('balance_amount', models.IntegerField(default=0)),
                ('statusA', models.CharField(max_length=60)),
                ('comment', models.TextField()),
                ('action', models.CharField(max_length=60)),
                ('preventive_action', models.TextField()),
                ('worked', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Reverted'), (2, 'Closed'), (3, 'Submitted')], default=3)),
                ('escalate_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
