# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='preventive_action',
            field=models.TextField(null=True),
        ),
    ]
