# Generated by Django 2.0 on 2018-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(2, 'Reverted'), (3, 'Closed'), (4, 'Submitted')], default=4, max_length=1),
        ),
    ]
