# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180315_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='action',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='worked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
