# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180314_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='form_user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
