# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180315_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
