# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180315_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='balance_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='billed_amount',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
